// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Data;

#nullable disable

namespace Web.Migrations
{
    [DbContext(typeof(CourseContext))]
    partial class CourseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FiftyMinPriceNTD")
                        .HasColumnType("int");

                    b.Property<string>("IntroImages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IntroVideoId")
                        .HasColumnType("int");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<int>("ReceivedReviews")
                        .HasColumnType("int");

                    b.Property<string>("SubTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrialPriceNTD")
                        .HasColumnType("int");

                    b.Property<int>("TwentyFiveMinPriceNTD")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Course");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "💰你是老师吗？ 获得折扣！🇬🇧 常驻利兹（英国） 🇺🇸 15 年以上国际经验 🌎 曾就职于谷歌、环球音乐和国际特赦组织 🤝 传播专家 👩🏻‍🎓\r\n获得学士学位、理学硕士和剑桥资格\r\n🥇找到你想要的工作 🔥 在顶尖大学学习 👑 克服你的恐惧 😎 找到你的声音🚀增强你的信心",
                            FiftyMinPriceNTD = 1624,
                            IntroImages = "[\"https://picsum.photos/id/210/350/220\",\"https://picsum.photos/id/250/350/220\"]",
                            IntroVideoId = 1,
                            MemberID = 1,
                            ReceivedReviews = 1064,
                            SubTitle = "今天变得冷静和自信",
                            Title = "Feds🥇顶级雅思| 批判性思维 |\r\n面试教练🥇",
                            TrialPriceNTD = 469,
                            TwentyFiveMinPriceNTD = 1000
                        },
                        new
                        {
                            Id = 2,
                            Description = "期待什麼：\r\n 😉定制課程\r\n 😃免費英語資源\r\n                  🤡80% 學生演講\r\n 😃保證改善\r\n 🌄有趣和友好的環境\r\n                    🌄額外的課外工作表和家庭作業（根據要求）\r\n😀 很多談話😁",
                            FiftyMinPriceNTD = 857,
                            IntroImages = "[\"https://picsum.photos/id/210/350/220\",\"https://picsum.photos/id/250/350/220\"]",
                            IntroVideoId = 2,
                            MemberID = 2,
                            ReceivedReviews = 328,
                            SubTitle = "25分钟儿童课程",
                            Title = "Todd🤠American Teacher!🏅Kid's English\r\n                          Expert! 🏅 Basic to Advanced😀",
                            TrialPriceNTD = 514,
                            TwentyFiveMinPriceNTD = 700
                        });
                });

            modelBuilder.Entity("Web.Models.IntroVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IntroVideo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Thumbnail = "~/image/thumb_nails/tutor001_thumbnail",
                            VideoUrl = "https://www.youtube.com/embed/3XToqdAcm9g"
                        },
                        new
                        {
                            Id = 2,
                            Thumbnail = "~/image/thumb_nails/tutor002_thumbnail",
                            VideoUrl = "https://www.youtube.com/embed/xXsfl6RBuhQ"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
